cross_app/cross_order/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^list_supplier/$', 'cross_app.cross_order.views.list_supplier'),
    (r'^list_order/$', 'cross_app.cross_order.views.list_order'),
    (r'^update_order_list/$', 'cross_app.cross_order.views.update_order_list'),
    (r'^transaction_list/$', 'cross_app.cross_order.views.transaction_list'),
    (r'^transaction_details/(?P<code>[\w-]+)/$', 'cross_app.cross_order.views.transaction_details'),
    (r'^update_trans_order_list/$', 'cross_app.cross_order.views.update_trans_order_list'),
    (r'^order_history/$', 'cross_app.cross_order.views.order_history'),
    (r'^exportOrders/$', 'cross_app.cross_order.views.exportExcelOrders'),
    (r'^exportTransactions/$', 'cross_app.cross_order.views.exportExcelTransactions'),
    (r'^exportExcelForSupplier/$', 'cross_app.cross_order.views.exportExcelForSupplier'),
    (r'^exportCsvTransaction/$', 'cross_app.cross_order.views.export_csv_transaction'),
    (r'^update_transaction_status/$', 'cross_app.cross_order.views.update_transaction_status'),
    (r'^report_list/$', 'cross_app.cross_order.views.report_list'),
    (r'^get_excel_report/$', 'cross_app.cross_order.views.get_excel_report'),
    (r'^order_search/$', 'cross_app.cross_order.views.order_search'),
    (r'^order_search_ajax/$', 'cross_app.cross_order.views.order_search_ajax'),
    (r'^add_invoice/$', 'cross_app.cross_order.views.add_invoice'),
    (r'^list_invoice/$', 'cross_app.cross_order.views.list_invoice'),
    (r'^update_invoice_status/$', 'cross_app.cross_order.views.update_invoice_status'),

)


cross_app/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from settings import DOCUMENT_ROOT

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^$', 'cross_app.userprofile.views.user_login'),
    (r'^user/', include('cross_app.userprofile.urls')),
    (r'^cross_order/', include('cross_app.cross_order.urls')),
    (r'^dms/', include('cross_app.dms.urls')),
    (r'^sms/', include('cross_app.sms.urls')),
    (r'^rts/', include('cross_app.rts.urls')),
    (r'^cts/', include('cross_app.cts.urls')),
    (r'^rosetta/', include('rosetta.urls')),
    (r'^sms/', include('cross_app.sms.urls')),
    (r'^main/', include('main.urls')),

    (r'^static/(.*)$', 'django.views.static.serve', {'document_root': '%s' % DOCUMENT_ROOT, 'show_indexes': True}),
)

cross_app/cross_order/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import  datetime
from django.db.models.signals import post_save
from django.utils.translation import gettext_lazy as _

class ColumnType():
    CHAR = 0
    INT = 1
    FLOAT = 2
    
    TYPE = (
            (CHAR,_("CHAR")),
            (INT ,_("INT")),
            (FLOAT ,_("FLOAT")),
            )

class ReportSql2Excel(models.Model):
    name = models.CharField(max_length=2000,null=True)
    excel_name = models.CharField(max_length=2000,null=True)
    tb_name = models.CharField(max_length=2000,null=True)

    isActive = models.BooleanField(null=False,default=True)
    order = models.IntegerField(default=9999)

    def __unicode__(self):
        return str(self.name)

class Sql2ExcelColumn(models.Model):
    report = models.ForeignKey(ReportSql2Excel,unique=False,null=False)
    name = models.CharField(max_length=2000,null=True)
    type = models.IntegerField(default=ColumnType.CHAR,choices=ColumnType.TYPE)

    def __unicode__(self):
        return str(self.name)

class ReportUnprocessedCrossDock(models.Model):
    id_sales_order_item = models.PositiveIntegerField(max_length=10,primary_key=True)
    suborder_number = models.CharField(max_length=20,null=True)
    order_nr = models.CharField(max_length=45,null=True)
    order_date = models.DateTimeField(blank=True)
    sku = models.CharField(max_length=255,null=True)
    barcode_ean = models.CharField(max_length=255,null=True)
    name = models.CharField(max_length=2000,null=False)
    attribute_set = models.CharField(max_length=50,null=False)
    bob_status = models.CharField(max_length=200,null=True)
    supplier_name = models.CharField(max_length=2000,null=False)

    def __unicode__(self):
        return str(self.sku)

    class Meta:
        db_table = 'unprocessed_crossdock_order_items'

class OverdueCrossDock(models.Model):
    id_sales_order_item = models.PositiveIntegerField(max_length=10,primary_key=True)
    suborder_number = models.CharField(max_length=20,null=True)
    order_nr = models.CharField(max_length=45,null=True)
    order_date = models.DateTimeField(blank=True)
    sku = models.CharField(max_length=255,null=True)
    barcode_ean = models.CharField(max_length=255,null=True)
    name = models.CharField(max_length=2000,null=False)
    attribute_set = models.CharField(max_length=50,null=False)
    bob_status = models.CharField(max_length=200,null=True)
    days_overdue = models.PositiveIntegerField(max_length=10)
    delivery_time_max = models.PositiveIntegerField(max_length=10)

    def __unicode__(self):
        return str(self.sku)

    class Meta:
        db_table = 'overdue_crossdock_order_items'

class ReportOutOfStockCrossDock(models.Model):
    id_sales_order_item = models.PositiveIntegerField(max_length=10,primary_key=True)
    suborder_number = models.CharField(max_length=20,null=True)
    order_nr = models.CharField(max_length=45,null=True)
    order_date = models.DateTimeField(blank=True)
    sku = models.CharField(max_length=255,null=True)
    barcode_ean = models.CharField(max_length=255,null=True)
    name = models.CharField(max_length=2000,null=False)
    attribute_set = models.CharField(max_length=50,null=False)
    bob_status = models.CharField(max_length=200,null=True)
    
    def __unicode__(self):
        return str(self.sku)

    class Meta:
        db_table = 'outofstock_crossdock_order_items'

class ReportConfirmedSupplierBase(models.Model):
    item_count = models.IntegerField()
    supplier_name = models.CharField(max_length=2000,null=False)

    def __unicode__(self):
        return str(self.supplier_name)

    class Meta:
        db_table = 'confirmed_number_of_items_supplier_base'

class ReportConfirmedSkuBase(models.Model):
    sku = models.CharField(max_length=255,null=True,primary_key=True)
    barcode_ean = models.CharField(max_length=255,null=True)
    item_count = models.IntegerField()
    name = models.CharField(max_length=2000,null=False)
    attribute_set = models.CharField(max_length=50,null=False)
    supplier_name = models.CharField(max_length=2000,null=False)

    def __unicode__(self):
        return str(self.sku)

    class Meta:
        db_table = 'confirmed_number_of_items_sku_base'
    

class Supplier(models.Model):
    name = models.CharField(max_length=1000,null=False)
    code  = models.CharField(max_length=100,null=False)
    

class CrossStatus(models.Model):
    name = models.CharField(max_length=250,null=False)
    isTransactionGenerate = models.BooleanField(null=False,default=False)
    isFinal = models.BooleanField(null=False,default=False)
    isInvalid = models.BooleanField(null=False,default=False)
    order = models.IntegerField(default=9999)

    def __unicode__(self):
        return str(self.name)

class EkolStock(models.Model):
    sku = models.CharField(max_length=250,null=False,primary_key=True)
    available_quantity = models.IntegerField(default=0,db_column='qtystock')
    stock_out_planned = models.IntegerField(default=0,db_column = 'qtystockoutplanned')
    class Meta:
        db_table = 'cross_ekol_stock'
    def __unicode__(self):
        return self.sku

class TransactionStatus(models.Model):
    name = models.CharField(max_length=250,null=False)
    order = models.IntegerField(default=9999)
    def __unicode__(self):
        return self.name

class OrderAttributeSet(models.Model):
    attributeName = models.CharField(max_length=50,null=False)
    attributeCode = models.CharField(max_length=50,null=False)
    isInvalid = models.BooleanField(null=False,default=False)
    createTime = models.DateTimeField(default= datetime.now())
    order = models.IntegerField(default=9999)
    def __unicode__(self):
        return str(self.attributeName)


class Order(models.Model):
    id_sales_order_item = models.PositiveIntegerField(max_length=10,null=False,default=0)
    id_sales_order = models.PositiveIntegerField(max_length=10,null=True)
    order_nr = models.CharField(max_length=45,null=True)
    size = models.CharField(max_length=45,null=True)
    sku = models.CharField(max_length=255,null=True)
    supplier = models.ForeignKey(Supplier,unique=False,null=False)
    sku_supplier_simple = models.CharField(max_length=50,null=True)
    shipment_type = models.CharField(max_length=255,null=True)
    barcode_ean = models.CharField(max_length=255,null=True)
    sku_supplier_config = models.CharField(max_length=50,null=True)
    buysheet_id = models.CharField(max_length=255,null=True)
    name = models.CharField(max_length=255,null=True)
    status = models.CharField(max_length=255,null=True)
    id_sales_order_item_shipment = models.PositiveIntegerField(max_length=10,null=True)
    tracking_url = models.CharField(max_length=255,null=True)
    suborder_number = models.CharField(max_length=20,null=True)
    paid_price = models.DecimalField(max_digits=10,decimal_places=2,null=False)
    cost = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    shipping_name = models.CharField(max_length=511,null=True)
    shipping_city = models.CharField(max_length=255,null=True)
    billing_name = models.CharField(max_length=511,null=True)
    billing_city = models.CharField(max_length=255,null=True)
    customer_first_name = models.CharField(max_length=255,null=True)
    customer_last_name = models.CharField(max_length=255,null=True)
    amount_paid = models.DecimalField(max_digits=10,decimal_places=2, null=False,default=0)
    tax_percent = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    original_unit_price = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    unit_price = models.DecimalField(max_digits=10,decimal_places=2, null=False)
    tax_amount = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    phone = models.CharField(max_length=255,null=True)
    coupon_money_value = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    coupon_percent = models.IntegerField(max_length=11,null=True)
    address1 = models.CharField(max_length=255,null=True)
    address2 = models.CharField(max_length=255,null=True)
    billing_address = models.CharField(max_length=255,null=True)
    billing_address2 = models.CharField(max_length=255,null=True)
    order_date = models.DateTimeField(blank=True)
    last_status_change = models.DateTimeField(blank=True,null=True)
    def __unicode__(self):
        return str(self.id_sales_order_item)

class OrderCrossDetails(models.Model):
    order = models.OneToOneField(Order,null=False)
    cross_status   = models.ForeignKey(CrossStatus,unique=False,null=False)

    supplier_order_date = models.DateTimeField(null=True,blank=True)
    order_attribute = models.CharField(max_length=10,null=False)
    inbound_order_number = models.CharField(max_length=30,null=True)
    comment = models.TextField(null=True)
    
    def __unicode__(self):
        return str(self.order)+' '+self.cross_status.name

class LastUpdate(models.Model):
    update_date = models.DateTimeField(blank=False)
    cross_status = models.ForeignKey(CrossStatus,unique=False,null=False)
    order = models.ForeignKey(Order)
    user = models.ForeignKey(User)

    class Meta:
        ordering = ['-update_date']

    def __unicode__(self):
       return str(self.order_id)+' changed to '+self.cross_status+' on '+str(self.update_date)+' by '+self.user.username

class Transactions(models.Model):
    code = models.CharField(max_length=255,null=True)
    create_date = models.DateTimeField(blank=False)
    create_user = models.ForeignKey(User)
    status   = models.ForeignKey(TransactionStatus,unique=False,null=False)
    def __unicode__(self):
        return str(self.code)

class InvoiceType(models.Model):

cross_app/cross_order/forms.py
from django import forms
from cross_order.models import CrossStatus, OrderAttributeSet
from django.utils.translation import gettext_lazy as _

class OrderSearchForm(forms.Form):
    order_item_id = forms.CharField(required = False,label=_("search_order_item_id"))
    zidaya_order_item = forms.CharField(required = False,label=_("search_zidaya_order_item"))
    sku = forms.CharField(required = False,label=_("search_sku"))

    suborder_number = forms.CharField(required = False,label=_("search_suborder_number"))
    supplier_name = forms.CharField(required = False,label=_("search_supplier_name"))

    supplier_sku_config = forms.CharField(required = False,label=_("search_cross_supplier_sku_config"))
    supplier_sku_simple = forms.CharField(required = False,label=_("search_cross_supplier_sku_simple"))
    barcode = forms.CharField(required = False,label=_("search_cross_barcode"))

    name = forms.CharField(required = False,label=_("search_cross_name"))
    order_date_start = forms.CharField(required = False,label=_("search_cross_order_date_start"))
    order_date_end = forms.CharField(required = False,label=_("search_cross_order_date_end"))

    inbound_order_number = forms.CharField(required = False,label=_("search_inbound_order_number"))
    supplier_order_date_start = forms.CharField(required = False,label=_("search_supplier_order_date_start"))
    supplier_order_date_end = forms.CharField(required = False,label=_("search_supplier_order_date_end"))

    last_update_date_start = forms.CharField(required = False,label=_("search_last_update_date_start"))
    last_update_date_end = forms.CharField(required = False,label=_("search_last_update_date_end"))
    #comment = forms.CharField(required = False,label=_("search_comment"))
    cross_status = forms.ModelChoiceField(label=_("search_cross_status"),queryset = CrossStatus.objects.all(),required=False,empty_label=_("search_all"))
    attribute_set = forms.ModelChoiceField(label=_("search_attribute_set"),queryset = OrderAttributeSet.objects.all(),required=False,empty_label=_("search_all"))


cross_app/templates/cross_order/list_invoice.html
{% extends "base.html" %}
{% load i18n %}
{% load helper %}
{% block extrahead %}
{#    <script type="text/javascript" src="{{ STATIC_URL }}js/popup-plugin.js"></script>#}
{% endblock %}

{% block content %}
    {% include "cross_order/boxes/add_invoice_box.html" %}
    <div class="tabbed">
        <div class="tab-content" style="display:block;">
            <div class="items">

                <form id="DateForm" method="POST" action="/cross_order/list_invoice/">
                    {% csrf_token %}
                    <table class="dateFilter" cellspacing="0" cellpadding="0">
                        <tr>
                            <td>
                                {% trans "start_date" %}
                            </td>
                            <td>
                                <input id="id_dateStart" type="textbox" name="dateStart" value="{{ start_date|date:"m/j/Y" }}"/>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                {% trans "end_date" %}
                            </td>
                            <td>
                                <input id="id_dateEnd" type="textbox" name="dateEnd" value="{{ end_date|date:"m/j/Y" }}"/>
                            </td>
                        </tr>
                        <tr>
                            <td>

                            </td>
                            <td style="text-align: right;">
                                <input id="id_submit" type="submit" name="submit" value="Sorgula" class="button"/>
                            </td>
                        </tr>

                    </table>
                </form>
                <div class="dateRangeInfo">
                    {{ start_date|date }} - {{ end_date|date }}
                </div>
                <form id ="invoiceUpdateForm" action="/cross_order/update_invoice_status/" method='post'>
                    {% csrf_token %}
                    <table id="invoiceList">
                        <thead>
                        <tr>
                            <th><input type=checkbox name='allSelect' class="allSelect"></th>
                            <th>
                                {% trans "Edit_Invoice" %}
                            </th>
                            <th>
                                {% trans "transaction_code" %}
                            </th>
                            <th>
                                {% trans "supplier_name" %}
                            </th>
                            <th>
                                {% trans "invoice_date" %}
                            </th>
                            <th>
                                {% trans "invoice_type" %}
                            </th>
                            <th>
                                {% trans "invoice_number" %}
                            </th>
                            <th>
                                {% trans "invoice_amount" %}
                            </th>
                            <th>
                                {% trans "invoice_currency" %}
                            </th>
                            <th>
                                {% trans "quantity_in_invoice" %}
                            </th>
                            <th>
                                {% trans "#create_user" %}
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for t in invoiceList %}
                            <tr>
                                <td><input type=checkbox class="checkboxClass" name='invoiceChecked' value="{{ t.pk }}"></td>
                                <td>
                                <span class="actionLabel" onclick="viewInvoiceBox(
                                        '{{ t.pk }}',
                                        '{{ t.trans.code }}',
                                        '{{ t.trans|getSupplierName }}',
                                        '{{ t.trans.pk }}',

                                        '{{ t.create_date }}',
                                        '{{ t.invoice_type.pk }}',

                                        '{{ t.invoice_number }}',
                                        '{{ t.invoice_amount }}',
                                        '{{ t.quantity_in_invoice }}',
                                        '{{ t.invoice_currency.pk }}'

                                        )">
                                   Edit Invoice
                                </span>
                                </td>
                                <td>
                                    <a href="/cross_order/transaction_details/{{ t.trans.code }}/">
                                        {{ t.trans.code }}
                                    </a>
                                </td>
                                <td>
                                    {{ t.trans|getSupplierName }}
                                </td>

                                <td>
                                    {{ t.create_date|date:"d/M/Y H:i:s" }}
                                </td>
                                <td>
                                    {{ t.invoice_type.type }}
                                </td>
                                <td>
                                    {{ t.invoice_number }}
                                </td>
                                <td>
                                    {{ t.invoice_amount }}
                                </td>
                                <td>
                                    {{ t.invoice_currency.currency }}
                                </td>
                                <td>
                                    {{ t.quantity_in_invoice }}
                                </td>
                                <td>
                                    {{ t.create_user.username }}
                                </td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <table class="actionPanel" cellpadding="0" cellspacing="0" width="100%">
                        <tr>
                            <td class="left">
                                <span class="actionLabel" onclick="deleteInvoices()">
                                   Delete Selected Invoice
                                </span>
                            </td>
                            <td  class="right">

                            </td>
                        </tr>
                    </table>


                </form>

                {% include "cross_order/boxes/confirm_deletion_of_invoices.html" %}
            </div>

        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
            $( "#id_dateStart" ).datepicker({ altFormat: 'yy-mm-dd' });
            $( "#id_dateEnd" ).datepicker({  altFormat: 'yy-mm-dd' });
            $( "#id_invoiceDate" ).datepicker({ altFormat: 'yy-mm-dd' });

            displayModuleMenus("cross","crossInvoice");
            setMenuName("{% trans module_cross_order_tracking_system %}");

            $('#invoiceList').dataTable(
                    {
                        "bJQueryUI": true,
                        "bPaginate":true,
                        "sPaginationType": "full_numbers",
                        "iDisplayLength": 25,
                        "aoColumnDefs":
                                [
                                    { "bSortable": false, "aTargets": [ 0 ] }

                        ]
                    }
            );
            $('.allSelect').click(function(){
                if($(this).is(':checked')){
                    $('.checkboxClass').attr("checked", 'checked');
                }
                else
                    $('.checkboxClass').attr("checked", "");
            })
        });
        function deleteInvoices(){
            if($("input:checked").length > 0)
            {
                $( "#dialog:ui-dialog" ).dialog( "destroy" );
                $( "#dialog-confirm" ).dialog({
                    resizable: false,
                    height:140,
                    modal: true,
                    buttons: {
                        "Evet": function() {
    //                        $('#id_buttonSource').val("status");
                            $( this ).dialog( "close" );
                            $('#invoiceUpdateForm').submit();
                        },
                        Hayir: function() {
                            $( this ).dialog( "close" );
                        }
                    }
                });
            }
        }
    </script>
{% endblock %}

cross_app/templates/cross_order/order_search.html
{% extends "base.html" %}
{% load i18n %}
{% load helper %}
{% block extrahead %}
{% endblock %}

{% block content %}
<div class="tabbed">
	<div class="tab-content" style="display:block;">
		<div class="items">
            <form id="SearchForm" action="/cross_order/order_search/" method="POST">
                {% csrf_token %}
                <div class="FormWrapper">
                <div>
                    <ul class="FormPosition">
                        {% for field in form.visible_fields %}
                            {% if "date" not in field.label and "Date" not in field.label %}
                                <li class="FormLineWrapper">
                                    <div class="FormObjectSearch">
                                        {% if field.errors %}
                                            {% for error in field.errors %}
                                                <div class="FormObject ErrorArea"> {{ error }}</div>
                                            {% endfor %}
                                        {% endif %}
                                        <div class="FormLabel">
                                            {{ field.label }}
                                        </div>
                                        <span id="id_{{ field.name }}" ></span>
                                    </div>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                    </div>
                <!--
                <div class="clear"></div>
                <div>
                    <ul class="FormPosition">
                        {% for field in form.visible_fields %}
                            {% if "_start" in field.name or "_Start" in field.name %}
                                <li class="FormLineWrapper">
                                    <div class="FormObjectSearch">
                                        {% if field.errors %}
                                            {% for error in field.errors %}
                                                <div class="FormObject ErrorArea"> {{ error }}</div>
                                            {% endfor %}
                                        {% endif %}
                                        <div class="FormLabel">
                                            {{ field.label }}
                                        </div>
                                        <div id="id_{{ field.name }}" ></div>
                                    </div>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                <div class="clear"></div>
                <div>
                    <ul class="FormPosition">
                        {% for field in form.visible_fields %}
                            {% if "_end" in field.name or "_End" in field.name %}
                                <li class="FormLineWrapper">
                                    <div class="FormObjectSearch">
                                        {% if field.errors %}
                                            {% for error in field.errors %}
                                                <div class="FormObject ErrorArea"> {{ error }}</div>
                                            {% endfor %}
                                        {% endif %}
                                        <div class="FormLabel">
                                            {{ field.label }}
                                        </div>
                                        <div id="id_{{ field.name }}" ></div>
                                    </div>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>
                -->
                <div class="clear"></div>
                <div style="text-align: right;">
                    <a class="submitButton" href="javascript:$.noop();" >
                            <span>{% trans "filter" %} </span>
                    </a>
                </div>
                </div>
                {% for field in form.hidden_fields %}
                    {{ field }}
                {% endfor %}
            </form>

<div class="clear"></div>
        <br/>   
            <table id="orderList">
                <thead>
                    <tr>
                        <th><input type=checkbox name='allSelect' class="allSelect"></th>
                        <th>{% trans "cross_status" %} </th>
                        <th>{% trans "supplier_name" %} </th>
                        <th>{% trans "order_item_id" %}</th>
                        <th>{% trans "zidaya_order_number" %}  </th>
                        <th>{% trans "suborder_number" %}  </th>
                        <th>{% trans "sku" %}</th>
                        <th>{% trans "size" %}</th>
                        <th>{% trans "supplier_sku_config" %}</th>
                        <th>{% trans "supplier_sku_simple" %}</th>
                        <th>{% trans "barcode" %}</th>
                        <th>{% trans "name" %}</th>
                        <th>{% trans "paid_price" %}</th>
                        <th>{% trans "cost" %}</th>
                        <th>{% trans "order_date" %}</th>
                        <th>{% trans "attribute_set" %}</th>
                        <th>{% trans "inbound_order_number" %}</th>
                        <th>{% trans "comment" %}</th>
                        <th>{% trans "supplier_order_date" %}</th>
                        <!--
                        <th>{% trans "last_update" %}</th>
                        -->
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
		</div>
	</div>
</div>


<script type="text/javascript">
    $(document).ready(function(){
        setMenuName("{% trans module_detailed_crossorder_item_search %}");

        var oTable = $('#orderList').dataTable(
                {
                    "sScrollY": "350px",
                    "sScrollX": "100%",
                    "bJQueryUI": true,
                    "sPaginationType": "full_numbers",
                    "bProcessing": true,
                    "bServerSide": true,
                    "sAjaxSource": "/cross_order/order_search_ajax/",
                    "aoColumnDefs": [
                      { 'bSortable': false, 'aTargets': [ 0 ] }
                   ]
                }
        ).columnFilter(
                {sPlaceHolder: "head:after",
                    aoColumns:[
                            null,
                            { sSelector:"#id_cross_status",type:"select", values: [{% for c in crossList %} '{{ c.name }}', {% endfor %} ]},
                            { sSelector:"#id_supplier_name"},
                            { sSelector:"#id_order_item_id"},
                            { sSelector:"#id_zidaya_order_item"},
                            { sSelector:"#id_suborder_number"},
                            { sSelector:"#id_sku"},
                            null,
                            { sSelector:"#id_supplier_sku_config"},
                            { sSelector:"#id_supplier_sku_simple"},
                            { sSelector:"#id_barcode"},
                            { sSelector:"#id_name"},
                            null,
                            null,
                            null,
                            { sSelector:"#id_attribute_set",type:"select", values: [{% for c in attributeList %} '{{ c.attributeCode }}', {% endfor %} ]},
                            { sSelector:"#id_inbound_order_number"},
                            null,
                                null,
                           // null
                    ]
                }
        );
        $("#orderList_filter").hide();

        $('.allSelect').click(function(){
            if($(this).is(':checked')){
                $('.checkboxClass').attr("checked", 'checked');
            }
            else
                $('.checkboxClass').attr("checked", "");
        });
    });
</script>
{% endblock %}