cross_app/cross_order/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^list_supplier/$', 'cross_app.cross_order.views.list_supplier'),
    (r'^list_order/$', 'cross_app.cross_order.views.list_order'),
    (r'^update_order_list/$', 'cross_app.cross_order.views.update_order_list'),
    (r'^transaction_list/$', 'cross_app.cross_order.views.transaction_list'),
    (r'^transaction_details/(?P<code>[\w-]+)/$', 'cross_app.cross_order.views.transaction_details'),
    (r'^update_trans_order_list/$', 'cross_app.cross_order.views.update_trans_order_list'),
    (r'^order_history/$', 'cross_app.cross_order.views.order_history'),
    (r'^exportOrders/$', 'cross_app.cross_order.views.exportExcelOrders'),
    (r'^exportTransactions/$', 'cross_app.cross_order.views.exportExcelTransactions'),
    (r'^exportExcelForSupplier/$', 'cross_app.cross_order.views.exportExcelForSupplier'),
    (r'^exportCsvTransaction/$', 'cross_app.cross_order.views.export_csv_transaction'),
    (r'^update_transaction_status/$', 'cross_app.cross_order.views.update_transaction_status'),
    (r'^report_list/$', 'cross_app.cross_order.views.report_list'),
    (r'^get_excel_report/$', 'cross_app.cross_order.views.get_excel_report'),
    (r'^order_search/$', 'cross_app.cross_order.views.order_search'),
    (r'^order_search_ajax/$', 'cross_app.cross_order.views.order_search_ajax'),
    (r'^add_invoice/$', 'cross_app.cross_order.views.add_invoice'),
    (r'^list_invoice/$', 'cross_app.cross_order.views.list_invoice'),
    (r'^update_invoice_status/$', 'cross_app.cross_order.views.update_invoice_status'),

)


cross_app/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from settings import DOCUMENT_ROOT

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^$', 'cross_app.userprofile.views.user_login'),
    (r'^user/', include('cross_app.userprofile.urls')),
    (r'^cross_order/', include('cross_app.cross_order.urls')),
    (r'^dms/', include('cross_app.dms.urls')),
    (r'^sms/', include('cross_app.sms.urls')),
    (r'^rts/', include('cross_app.rts.urls')),
    (r'^cts/', include('cross_app.cts.urls')),
    (r'^rosetta/', include('rosetta.urls')),
    (r'^sms/', include('cross_app.sms.urls')),
    (r'^main/', include('main.urls')),

    (r'^static/(.*)$', 'django.views.static.serve', {'document_root': '%s' % DOCUMENT_ROOT, 'show_indexes': True}),
)

cross_app/cross_order/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import  datetime
from django.db.models.signals import post_save
from django.utils.translation import gettext_lazy as _

class ColumnType():
    CHAR = 0
    INT = 1
    FLOAT = 2
    
    TYPE = (
            (CHAR,_("CHAR")),
            (INT ,_("INT")),
            (FLOAT ,_("FLOAT")),
            )

class ReportSql2Excel(models.Model):
    name = models.CharField(max_length=2000,null=True)
    excel_name = models.CharField(max_length=2000,null=True)
    tb_name = models.CharField(max_length=2000,null=True)

    isActive = models.BooleanField(null=False,default=True)
    order = models.IntegerField(default=9999)

    def __unicode__(self):
        return str(self.name)

class Sql2ExcelColumn(models.Model):
    report = models.ForeignKey(ReportSql2Excel,unique=False,null=False)
    name = models.CharField(max_length=2000,null=True)
    type = models.IntegerField(default=ColumnType.CHAR,choices=ColumnType.TYPE)

    def __unicode__(self):
        return str(self.name)

class ReportUnprocessedCrossDock(models.Model):
    id_sales_order_item = models.PositiveIntegerField(max_length=10,primary_key=True)
    suborder_number = models.CharField(max_length=20,null=True)
    order_nr = models.CharField(max_length=45,null=True)
    order_date = models.DateTimeField(blank=True)
    sku = models.CharField(max_length=255,null=True)
    barcode_ean = models.CharField(max_length=255,null=True)
    name = models.CharField(max_length=2000,null=False)
    attribute_set = models.CharField(max_length=50,null=False)
    bob_status = models.CharField(max_length=200,null=True)
    supplier_name = models.CharField(max_length=2000,null=False)

    def __unicode__(self):
        return str(self.sku)

    class Meta:
        db_table = 'unprocessed_crossdock_order_items'

class OverdueCrossDock(models.Model):
    id_sales_order_item = models.PositiveIntegerField(max_length=10,primary_key=True)
    suborder_number = models.CharField(max_length=20,null=True)
    order_nr = models.CharField(max_length=45,null=True)
    order_date = models.DateTimeField(blank=True)
    sku = models.CharField(max_length=255,null=True)
    barcode_ean = models.CharField(max_length=255,null=True)
    name = models.CharField(max_length=2000,null=False)
    attribute_set = models.CharField(max_length=50,null=False)
    bob_status = models.CharField(max_length=200,null=True)
    days_overdue = models.PositiveIntegerField(max_length=10)
    delivery_time_max = models.PositiveIntegerField(max_length=10)

    def __unicode__(self):
        return str(self.sku)

    class Meta:
        db_table = 'overdue_crossdock_order_items'

class ReportOutOfStockCrossDock(models.Model):
    id_sales_order_item = models.PositiveIntegerField(max_length=10,primary_key=True)
    suborder_number = models.CharField(max_length=20,null=True)
    order_nr = models.CharField(max_length=45,null=True)
    order_date = models.DateTimeField(blank=True)
    sku = models.CharField(max_length=255,null=True)
    barcode_ean = models.CharField(max_length=255,null=True)
    name = models.CharField(max_length=2000,null=False)
    attribute_set = models.CharField(max_length=50,null=False)
    bob_status = models.CharField(max_length=200,null=True)
    
    def __unicode__(self):
        return str(self.sku)

    class Meta:
        db_table = 'outofstock_crossdock_order_items'

class ReportConfirmedSupplierBase(models.Model):
    item_count = models.IntegerField()
    supplier_name = models.CharField(max_length=2000,null=False)

    def __unicode__(self):
        return str(self.supplier_name)

    class Meta:
        db_table = 'confirmed_number_of_items_supplier_base'

class ReportConfirmedSkuBase(models.Model):
    sku = models.CharField(max_length=255,null=True,primary_key=True)
    barcode_ean = models.CharField(max_length=255,null=True)
    item_count = models.IntegerField()
    name = models.CharField(max_length=2000,null=False)
    attribute_set = models.CharField(max_length=50,null=False)
    supplier_name = models.CharField(max_length=2000,null=False)

    def __unicode__(self):
        return str(self.sku)

    class Meta:
        db_table = 'confirmed_number_of_items_sku_base'
    

class Supplier(models.Model):
    name = models.CharField(max_length=1000,null=False)
    code  = models.CharField(max_length=100,null=False)
    

class CrossStatus(models.Model):
    name = models.CharField(max_length=250,null=False)
    isTransactionGenerate = models.BooleanField(null=False,default=False)
    isFinal = models.BooleanField(null=False,default=False)
    isInvalid = models.BooleanField(null=False,default=False)
    order = models.IntegerField(default=9999)

    def __unicode__(self):
        return str(self.name)

class EkolStock(models.Model):
    sku = models.CharField(max_length=250,null=False,primary_key=True)
    available_quantity = models.IntegerField(default=0,db_column='qtystock')
    stock_out_planned = models.IntegerField(default=0,db_column = 'qtystockoutplanned')
    class Meta:
        db_table = 'cross_ekol_stock'
    def __unicode__(self):
        return self.sku

class TransactionStatus(models.Model):
    name = models.CharField(max_length=250,null=False)
    order = models.IntegerField(default=9999)
    def __unicode__(self):
        return self.name

class OrderAttributeSet(models.Model):
    attributeName = models.CharField(max_length=50,null=False)
    attributeCode = models.CharField(max_length=50,null=False)
    isInvalid = models.BooleanField(null=False,default=False)
    createTime = models.DateTimeField(default= datetime.now())
    order = models.IntegerField(default=9999)
    def __unicode__(self):
        return str(self.attributeName)


class Order(models.Model):
    id_sales_order_item = models.PositiveIntegerField(max_length=10,null=False,default=0)
    id_sales_order = models.PositiveIntegerField(max_length=10,null=True)
    order_nr = models.CharField(max_length=45,null=True)
    size = models.CharField(max_length=45,null=True)
    sku = models.CharField(max_length=255,null=True)
    supplier = models.ForeignKey(Supplier,unique=False,null=False)
    sku_supplier_simple = models.CharField(max_length=50,null=True)
    shipment_type = models.CharField(max_length=255,null=True)
    barcode_ean = models.CharField(max_length=255,null=True)
    sku_supplier_config = models.CharField(max_length=50,null=True)
    buysheet_id = models.CharField(max_length=255,null=True)
    name = models.CharField(max_length=255,null=True)
    status = models.CharField(max_length=255,null=True)
    id_sales_order_item_shipment = models.PositiveIntegerField(max_length=10,null=True)
    tracking_url = models.CharField(max_length=255,null=True)
    suborder_number = models.CharField(max_length=20,null=True)
    paid_price = models.DecimalField(max_digits=10,decimal_places=2,null=False)
    cost = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    shipping_name = models.CharField(max_length=511,null=True)
    shipping_city = models.CharField(max_length=255,null=True)
    billing_name = models.CharField(max_length=511,null=True)
    billing_city = models.CharField(max_length=255,null=True)
    customer_first_name = models.CharField(max_length=255,null=True)
    customer_last_name = models.CharField(max_length=255,null=True)
    amount_paid = models.DecimalField(max_digits=10,decimal_places=2, null=False,default=0)
    tax_percent = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    original_unit_price = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    unit_price = models.DecimalField(max_digits=10,decimal_places=2, null=False)
    tax_amount = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    phone = models.CharField(max_length=255,null=True)
    coupon_money_value = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    coupon_percent = models.IntegerField(max_length=11,null=True)
    address1 = models.CharField(max_length=255,null=True)
    address2 = models.CharField(max_length=255,null=True)
    billing_address = models.CharField(max_length=255,null=True)
    billing_address2 = models.CharField(max_length=255,null=True)
    order_date = models.DateTimeField(blank=True)
    last_status_change = models.DateTimeField(blank=True,null=True)
    def __unicode__(self):
        return str(self.id_sales_order_item)

class OrderCrossDetails(models.Model):
    order = models.OneToOneField(Order,null=False)
    cross_status   = models.ForeignKey(CrossStatus,unique=False,null=False)

    supplier_order_date = models.DateTimeField(null=True,blank=True)
    order_attribute = models.CharField(max_length=10,null=False)
    inbound_order_number = models.CharField(max_length=30,null=True)
    comment = models.TextField(null=True)
    
    def __unicode__(self):
        return str(self.order)+' '+self.cross_status.name

class LastUpdate(models.Model):
    update_date = models.DateTimeField(blank=False)
    cross_status = models.ForeignKey(CrossStatus,unique=False,null=False)
    order = models.ForeignKey(Order)
    user = models.ForeignKey(User)

    class Meta:
        ordering = ['-update_date']

    def __unicode__(self):
       return str(self.order_id)+' changed to '+self.cross_status+' on '+str(self.update_date)+' by '+self.user.username

class Transactions(models.Model):
    code = models.CharField(max_length=255,null=True)
    create_date = models.DateTimeField(blank=False)
    create_user = models.ForeignKey(User)
    status   = models.ForeignKey(TransactionStatus,unique=False,null=False)
    def __unicode__(self):
        return str(self.code)

class InvoiceType(models.Model):

cross_app/cross_order/forms.py
from django import forms
from cross_order.models import CrossStatus, OrderAttributeSet
from django.utils.translation import gettext_lazy as _

class OrderSearchForm(forms.Form):
    order_item_id = forms.CharField(required = False,label=_("search_order_item_id"))
    zidaya_order_item = forms.CharField(required = False,label=_("search_zidaya_order_item"))
    sku = forms.CharField(required = False,label=_("search_sku"))

    suborder_number = forms.CharField(required = False,label=_("search_suborder_number"))
    supplier_name = forms.CharField(required = False,label=_("search_supplier_name"))

    supplier_sku_config = forms.CharField(required = False,label=_("search_cross_supplier_sku_config"))
    supplier_sku_simple = forms.CharField(required = False,label=_("search_cross_supplier_sku_simple"))
    barcode = forms.CharField(required = False,label=_("search_cross_barcode"))

    name = forms.CharField(required = False,label=_("search_cross_name"))
    order_date_start = forms.CharField(required = False,label=_("search_cross_order_date_start"))
    order_date_end = forms.CharField(required = False,label=_("search_cross_order_date_end"))

    inbound_order_number = forms.CharField(required = False,label=_("search_inbound_order_number"))
    supplier_order_date_start = forms.CharField(required = False,label=_("search_supplier_order_date_start"))
    supplier_order_date_end = forms.CharField(required = False,label=_("search_supplier_order_date_end"))

    last_update_date_start = forms.CharField(required = False,label=_("search_last_update_date_start"))
    last_update_date_end = forms.CharField(required = False,label=_("search_last_update_date_end"))
    #comment = forms.CharField(required = False,label=_("search_comment"))
    cross_status = forms.ModelChoiceField(label=_("search_cross_status"),queryset = CrossStatus.objects.all(),required=False,empty_label=_("search_all"))
    attribute_set = forms.ModelChoiceField(label=_("search_attribute_set"),queryset = OrderAttributeSet.objects.all(),required=False,empty_label=_("search_all"))


cross_app/templates/cross_order/boxes/add_invoice_box.html
{% load i18n %}
<div class="invoiceBox" style="display:none;" title="Add Invoice">
    <div class="black_overlay" id="fade"></div>
    <div class="white_content">
        <div style="border-bottom: 1px solid #333333;margin-bottom: 10px;text-align: left;">
            {% trans "Add Invoice" %}
        </div>

        <div class="FormWrapper">
            <ul class="FormPosition">
                <li class="FormLineWrapper invoiceItemFormLine">
                    <div class="FormObjectSearch">
                        <div class="FormLabel">
                            {% trans "transaction_code" %}
                        </div>
                        <div>
                            <span id="id_transactionCode"></span>
                        </div>
                    </div>
                </li>
                <li class="FormLineWrapper invoiceItemFormLine">
                    <div class="FormObjectSearch">
                        <div class="FormLabel">
                            {% trans "Supplier" %}
                        </div>
                        <div>
                            <span id="id_transactionSupplierName"></span>
                        </div>
                    </div>
                </li>

                <form id ="id_invoiceForm" action="/cross_order/add_invoice/" method='post'>
                    {% csrf_token %}
                <li class="FormLineWrapper invoiceItemFormLine">
                    <div class="FormObjectSearch">
                        <div  type="hidden" class="FormLabel">
                            Invoice Date
                        </div>
                        <div>
                            <input id="id_invoiceDate" type="textbox" name="invoiceDate" value="{{ invoice_date|date:"m/j/Y" }}"/>
                        </div>
                    </div>
                </li>

                <li class="FormLineWrapper invoiceItemFormLine">
                    <div class="FormObjectSearch">
                        <div  type="hidden" class="FormLabel">
                            {% trans "Invoice_Type" %}
                        </div>
                        <div>
                            <select name='invoiceType' id='id_invoiceType'>
                                {% for it in invoiceTypeList %}
                                    <option value='{{ it.pk }}'>{{ it.type }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </li>

                <li class="FormLineWrapper invoiceItemFormLine">
                    <div class="FormObjectSearch">
                        <div  type="hidden" class="FormLabel">
                            {% trans "Invoice_Number" %}
                        </div>
                        <div>
                            <input style="height: 12px;" id="id_transactionInvoiceNumber" name="transactionInvoiceNumber" />
                        </div>
                    </div>
                </li>
                <li class="FormLineWrapper invoiceItemFormLine">
                    <div class="FormObjectSearch">
                        <div  type="hidden" class="FormLabel">
                            {% trans "Invoice_Amount" %}
                        </div>
                        <div>
                            <input id="id_transactionInvoiceAmount" name="transactionInvoiceAmount" />
                            <span id="id_error_amount" class="error_message"  style="display:none;">
                                Fatura yanlis. Tutari '.' ile ayiriniz.
                            </span>
                        </div>

                    </div>
                </li>
                <li class="FormLineWrapper invoiceItemFormLine">
                    <div class="FormObjectSearch">
                        <div  type="hidden" class="FormLabel">
                            {% trans "Invoice_Currency" %}
                        </div>
                        <div>
                            <select name='invoiceCurrency' id='id_invoiceCurrency'>
                                {% for ic in invoiceCurrencyList %}
                                    <option value='{{ ic.pk }}'>{{ ic.currency }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </li>
                <li class="FormLineWrapper invoiceItemFormLine">
                    <div class="FormObjectSearch">
                        <div  type="hidden" class="FormLabel">
                            {% trans "Quantity in Invoice" %}
                        </div>
                        <div>
                            <input id="id_transactionInvoiceQuantity" name="transactionInvoiceQuantity" />
                            <span id="id_error_quantity" class="error_message"  style="display:none;">
                                Fatura adedi yanlis. Lutfen sayi giriniz.
                            </span>
                        </div>
                    </div>
                </li>
                    <input type="hidden" value="" id="id_transactionID" name="transactionID" />
                    <input type="hidden" value="" id="id_invoiceID" name="invoiceID" />
                </form>

            </ul>
        </div>

        <div  style="float:right;margin-left: 10px;">
            <a href="#" onclick="return closeInvoiceBox();">
                {% trans "close" %}
            </a>
        </div>
        <div class="closeButton">
            <div style="float:right;">
                <a href="#" onclick="return submitInvoiceForm();" class="submitButton">
                    <span> {% trans "save" %} </span> {# translation needed #}
                </a>
            </div>
        </div>

    </div>
</div>

cross_app/templates/cross_order/boxes/confirm_box.html
{% load i18n %}
<div id="dialog-confirm" title="Onay" style="display:none;">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
        {% trans "supplier_informed_alert_message" %}
    </p>
</div>

cross_app/templates/cross_order/boxes/confirm_box_for_delete.html
{% load i18n %}
<div id="dialog-confirm" title="Onay" style="display:none;">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
        Dosya/lar kalıcı olarak silinecektir. Onaylıyor musunuz?
    </p>
</div>

cross_app/templates/cross_order/boxes/refunded_item_box.html
{% load i18n %}
<div class="refundBox" style="display:none;" title="Edit Order With SKU : {{ o.sku }}">
    <div class="black_overlay" id="fade"></div>
    <div class="white_content">
        <div style="border-bottom: 1px solid #333333;margin-bottom: 10px;text-align: left;">
           {% trans "refund_orderitem_header" %}
         </div>

        <div class="FormWrapper">
            <ul class="FormPosition">
                <li class="FormLineWrapper ReturnedItemFormLine">
                    <div class="FormObjectSearch">
                        <div class="FormLabel">
                           {% trans "order_nr" %}
                        </div>
                        <div>
                            <span id="id_refundedOrderNumber"></span>
                        </div>
                    </div>
                </li>
                <li class="FormLineWrapper ReturnedItemFormLine">
                    <div class="FormObjectSearch">
                        <div class="FormLabel">
                            {% trans "id_sales" %}
                        </div>
                        <div>
                            <span id="id_refundedIdSalesOrderItem"></span>
                        </div>
                    </div>
                </li>
                <li class="FormLineWrapper ReturnedItemFormLine">
                    <div class="FormObjectSearch">
                        <div class="FormLabel">
                            {% trans "sku" %}
                        </div>
                        <div>
                            <span id="id_refundedSku"></span>
                        </div>
                    </div>
                </li>

                    <li class="FormLineWrapper ReturnedItemFormLine paymentTypeWrapper">
                        <div class="FormObjectSearch">
                            <div class="FormLabel">
                                {% trans "payment_type" %}
                            </div>
                            <div>
                                <span id="id_paymentType" style="color:red;"></span>
                            </div>
                        </div>
                    </li>
                <form id ="refundedOrderForm" action="/rts/update_refunded_order/" method='post'>
                    {% csrf_token %}
                    <li class="FormLineWrapper ReturnedItemFormLine refundRefNumberWrapper">
                        <div class="FormObjectSearch">
                            <div class="FormLabel">
                                {% trans "refund_reference_number" %}
                            </div>
                            <div>
                                <input type="textbox" name="refundReferenceNumber" id = "id_refundReferenceNumber" value="">
                            </div>
                        </div>
                    </li>
                    <li class="FormLineWrapper ReturnedItemFormLine">
                        <div class="FormObjectSearch">
                            <div class="FormLabel">
                                {% trans "customer_contacted" %}
                            </div>
                            <div>
                                <select name='customerContacted' id='id_customerContactedList'>
                                    <option value='No'>{% trans "no" %}</option> {# translation needed #}
                                    <option value='Phone'>{% trans "via_phone" %}</option>
                                    <option value='Email'>{% trans "via_email" %}</option>
                                </select>
                            </div>
                        </div>
                    </li>
                    <li class="FormLineWrapper ReturnedItemFormLine">
                        <div class="FormObjectSearch">
                            <div class="FormLabel">
                                {% trans "is_coupon_needed" %}
                            </div>
                            <div style="text-align: left;">
                                <input type=checkbox name='isCouponNeeded' id= 'id_refundedIsCouponNeeded'>
                            </div>
                        </div>
                    </li>
                    <li class="FormLineWrapper ReturnedItemFormLine">
                        <div class="FormObjectSearch">
                            <div class="FormLabel">
                                {% trans "new_coupon_code" %}
                            </div>
                            <div>
                                <input type="textbox" name="newCoupon" value="" id="id_newCoupon">
                            </div>
                        </div>
                    </li>
                    <li class="FormLineWrapper ReturnedItemFormLine">
                        <div class="FormObjectSearch">
                            <div class="FormLabel">
                                {% trans "comment" %}
                            </div>
                            <div>
                                <textarea id="id_comment" name="comment" cols="30" rows="5"></textarea>
                            </div>
                        </div>
                    </li>
                 <input type="hidden" value="" id="id_returnedItemID" name="returnedItemID" />
                </form>
            </ul>
        </div>

        <div  style="float:right;margin-left: 10px;">
                <a href="#" onclick="return closeRefundBox();">
                    {% trans "close" %}
                </a>
            </div>
        <div class="closeButton">
            <div style="float:right;">
                <a href="#" onclick="return submitRefundedForm();" class="submitButton">
                    <span> {% trans "update_returned_item" %} </span> {# translation needed #}
                </a>
            </div>
        </div>
    </div>
</div>

cross_app/templates/cross_order/boxes/shipment_confirm_date.html
{% load i18n %}
<div class="confirmDateShipmentBox" style="display:none;" title="">
    <div class="black_overlay" id="fade"></div>
    <div class="white_content">
        <div style="border-bottom: 1px solid #333333;margin-bottom: 10px;text-align: left;">
            {% trans "confirm_shipment_date" %}
        </div>

        <div class="FormWrapper">
            <ul class="FormPosition">
                <li class="FormLineWrapper ReturnedItemFormLine">
                    <div class="FormObjectSearch">
                        <div class="FormLabel">
                            {% trans "shipment_number" %}
                        </div>
                        <div>
                            <span id="id_shipmentNumber"></span>
                        </div>
                    </div>
                </li>
                <li class="FormLineWrapper ReturnedItemFormLine">
                    <div class="FormObjectSearch">
                        <div class="FormLabel">
                            {% trans "supplier" %}
                        </div>
                        <div>
                            <span id="id_supplier"></span>
                        </div>
                    </div>
                </li>
                <li class="FormLineWrapper ReturnedItemFormLine">
                    <div class="FormObjectSearch">
                        <div class="FormLabel">
                            {% trans "proposed_shipment_date" %}
                        </div>
                        <div>
                            <span id="id_proposedDate"></span>
                        </div>
                    </div>
                </li>
                <li class="FormLineWrapper ReturnedItemFormLine">
                    <div class="FormObjectSearch">
                        <div class="FormLabel">
                            {% trans "total_item_proposed_date" %}
                        </div>
                        <div>
                            <span id="id_totalItemOnProposedDate"></span>
                        </div>
                    </div>
                </li>
                <li class="FormLineWrapper ReturnedItemFormLine">
                    <div class="FormObjectSearch">
                        <div class="FormLabel">
                            {% trans "create_user" %}
                        </div>
                        <div>
                            <span id="id_createUser"></span>
                        </div>
                    </div>
                </li>

                <form id ="confirmShipmentDate" action="/sms/confirm_shipment/" method='post'>
                    {% csrf_token %}

                    <li class="FormLineWrapper ReturnedItemFormLine">
                        <div class="FormObjectSearch">
                            <div  type="hidden" class="FormLabel">
                                {% trans "confirm_shipment_date" %}
                            </div>
                            <div>
                                <input id="id_confirmedShipmentDate" type="textbox" name="confirmedShipmentDate"/>
                            </div>
                        </div>
                    </li>
                    <li class="FormLineWrapper ReturnedItemFormLine">
                        <div class="FormObjectSearch">
                            <div class="FormLabel">
                                {% trans "comment" %}
                            </div>
                            <div>
                                <textarea id="id_Comment" name="comment" cols="94" rows="10"></textarea><br>
                            </div>
                        </div>
                    </li>
                    <input type="hidden" value="" id="id_shipmentID" name="sid" />
                </form>
            </ul>
        </div>

        <div style="float:right;margin-left: 10px;">
            <a href="#" onclick="return closeConfirmDateShipmentBox();">
                {% trans "close" %}
            </a>
        </div>
        <div class="closeButton">
            <div style="float:right;">
                <a href="#" onclick="return submitConfirmDateShipmentForm();" class="submitButton">
                    <span> Confirm </span> {# translation needed #}
                </a>
            </div>
        </div>
    </div>
</div>