cross_app/cts/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'^cancel_item/$', 'cross_app.cts.views.cancel_item'),
    (r'^cancel_mass/$', 'cross_app.cts.views.cancel_mass'),
)

cross_app/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from settings import DOCUMENT_ROOT

admin.autodiscover()

urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^$', 'cross_app.userprofile.views.user_login'),
    (r'^user/', include('cross_app.userprofile.urls')),
    (r'^cross_order/', include('cross_app.cross_order.urls')),
    (r'^dms/', include('cross_app.dms.urls')),
    (r'^sms/', include('cross_app.sms.urls')),
    (r'^rts/', include('cross_app.rts.urls')),
    (r'^cts/', include('cross_app.cts.urls')),
    (r'^rosetta/', include('rosetta.urls')),
    (r'^sms/', include('cross_app.sms.urls')),
    (r'^main/', include('main.urls')),

    (r'^static/(.*)$', 'django.views.static.serve', {'document_root': '%s' % DOCUMENT_ROOT, 'show_indexes': True}),
)

cross_app/cts/models.py
from django.db import models
from cross_app.cross_order.models import Supplier
from django.contrib.auth.models import User
from datetime import  datetime
from django.db.models.signals import post_save
from django.utils.translation import gettext_lazy as _
import settings

class OrderItemBaseForCancellation(models.Model):
    id_sales_order_item = models.PositiveIntegerField(max_length=10,null=False,default=0,unique=True,primary_key=True)
    id_sales_order = models.PositiveIntegerField(max_length=10,null=True)
    id_catalog_simple = models.IntegerField(max_length=11,null=False)
    id_catalog_config = models.IntegerField(max_length=11)
    order_nr = models.CharField(max_length=45,null=True)
    sku = models.CharField(max_length=255,null=True)
    order_date = models.DateTimeField(blank=True)
    supplier_id = models.PositiveIntegerField(max_length=10,default=0)
    supplier_name = models.CharField(max_length=511,null=True)
    barcode_ean = models.CharField(max_length=255,null=True)
    name = models.CharField(max_length=255,null=True)
    suborder_number = models.CharField(max_length=20,null=True)
    paid_price = models.DecimalField(max_digits=10,decimal_places=2,null=False)
    customer_email = models.CharField(max_length=511,null=True)
    billing_name = models.CharField(max_length=511,null=True)
    billing_address = models.CharField(max_length=255,null=True)
    billing_address2 = models.CharField(max_length=255,null=True)
    billing_city = models.CharField(max_length=255,null=True)
    billing_phone = models.CharField(max_length=255,null=True)

    shipping_name = models.CharField(max_length=511,null=True)
    shipping_address = models.CharField(max_length=255,null=True)
    shipping_address2 = models.CharField(max_length=255,null=True)
    shipping_city = models.CharField(max_length=255,null=True)
    shipping_phone = models.CharField(max_length=255,null=True)

    payment_method = models.CharField(max_length=511,null=True)
    coupon_code = models.CharField(max_length=511,null=True)
    coupon_money_value = models.DecimalField(max_digits=10,decimal_places=2, null=True)
    coupon_percent = models.IntegerField(max_length=11,null=True)
    bob_status = models.CharField(max_length=255,null=True)

    def __unicode__(self):
        return str(self.id_sales_order_item)

    class Meta:
        db_table = 'orderitem_base_for_cancellation'


class CancelReason(models.Model):
    name = models.CharField(max_length=250,null=False)
    isInvalid = models.BooleanField(null=False,default=False)
    order = models.IntegerField(default=9999)
    def __unicode__(self):
        return self.name

class cts_status():

    RETURNED = 0
    REFUNDED = 1
    COUPON_PENDING = 2
    RETURN_DENIED = 3

    TYPE = (
        (RETURNED ,_("RTS_RETURNED")),
        (REFUNDED,_("RTS_REFUNDED")),
        (COUPON_PENDING,_("RTS_COUPON_PENDING")),
        (RETURN_DENIED ,_("RTS_RETURN_DENIED")),
        )

class CancelItemDetails(models.Model):
    order_item = models.OneToOneField(OrderItemBaseForCancellation, to_field='id_sales_order_item',unique=True,null=False)
    cancel_reason = models.ForeignKey(CancelReason,unique=False,null=True)

    create_date = models.DateTimeField(default= datetime.now())
    create_user = models.ForeignKey(User, related_name='%(class)s_user_create')

    def __unicode__(self):
        return self.order_item.name + ' ' + self.cancel_reason.name

cross_app/cts/views.py
from datetime import  datetime,time,timedelta
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import redirect
from cross_order.helper_functions import render_response
#from dms.forms import DocumentUploadForm
from cross_order.utils import check_permission
from cts.models import CancelItemDetails, CancelReason, OrderItemBaseForCancellation
from settings import MEDIA_ROOT, LOGIN_URL

@login_required
def cancel_item(request):
    oii = request.GET.get('order_item_id','')   #order item id

    dict = {
        'reasonList':CancelReason.objects.all().order_by("order"),
        'suborder_nr':oii
    }

    if request.method == 'GET' and oii != '':
        cri = request.GET.get('cancelReason','')
        oib = OrderItemBaseForCancellation.objects.get(id_sales_order_item = int(oii) )
        cr = CancelReason.objects.get(pk = int(cri) )
        cid = CancelItemDetails()
        cid.order_item = oib
        cid.cancel_reason = cr
        cid.create_user = request.user
        cid.create_date = datetime.now()
        cid.save()

    return render_response(request, 'cts/home_cancellation.html',dict)

@login_required
def cancel_mass(request):

    dict = {
        'reasonList':CancelReason.objects.all().order_by("order")
    }

    if request.method == 'POST':
         order_item = request.POST['order_item']
         order_item_list = order_item.split("\r\n")

         for oi in order_item_list:
             oi = oi.lstrip().rstrip()
             cri = request.POST.get('cancelReason')
             oib = OrderItemBaseForCancellation.objects.get(id_sales_order_item = int(oi) )
             cr = CancelReason.objects.get(pk = int(cri) )
             cid = CancelItemDetails()
             cid.order_item = oib
             cid.cancel_reason = cr
             cid.create_user = request.user
             cid.create_date = datetime.now()
             cid.save()

    return render_response(request, 'cts/mass_cancel.html',dict)

cross_app/templates/cts/home_cancellation.html
{% extends "base.html" %}
{% load i18n %}
{% load helper %}
{% block extra_head %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/popup-plugin.js"></script>
{% endblock %}

{% block content %}
    <br/>
    <form id="cancelOrderItemForm" action="/cts/cancel_item/" method="GET">
        {% csrf_token %}
        <table class="actionPanel searchPanel" cellpadding="0" cellspacing="0" width="100%">

            <tr>
                <td style="background-color: none;">
                    {% trans "order_item_id" %}
                    <input id="cts_snr_search" type="textbox" name="order_item_id" value=""/>
                </td>
                <td>
                    <select name='cancelReason' id='id_cancelReason'>
                        <option value='all'>{% trans "Pick a Cancel Reason" %}</option>
                        {% for reason in reasonList %}
                            <option value='{{ reason.pk }}'>{{ reason.name }}</option>
                        {% endfor %}
                    </select>
                </td>
                <td>
                    <a class="submitButton" onclick="return cts_cancel();">
                        <span> {% trans "Cancel Item" %} </span>
                    </a>
                </td>
            </tr>
        </table>
        <script type="text/javascript">
            function cts_cancel(){
                $('#id_buttonSource').val("search");
                $('#cancelOrderItemForm').submit();
            }
        </script>
    </form>
    <script type="text/javascript">
        $(document).ready(function(){
            displayModuleMenus("rts","rtsWarehouse");
            setMenuName("{% trans rts_submenu_left_top_warehouse %}");

            var oTable = $('#orderList').dataTable(
                    {
                        "sScrollY": "320px",
                        "bJQueryUI": true,
                        "sPaginationType": "full_numbers",
                        "sScrollX": "100%"
                    }
            );
            $('#rts_snr_search').val("{{ suborder_nr }}");
            $('.checkboxClass').attr("checked", "");
            $('.allSelect').click(function(){
                if($(this).is(':checked')){
                    $('.checkboxClass').attr("checked", 'checked');
                }
                else
                    $('.checkboxClass').attr("checked", "");
            });
        });
    </script>

{% endblock %}

cross_app/templates/cts/mass_cancel.html
{% extends "base.html" %}
{% load i18n %}
{% load helper %}
{% block extrahead %}
{% endblock %}

{% block content %}
    <div class="tabbed">
        <div class="tab-content" style="display:block;">
            <div class="items">
                <div style="float: left; width: 500px;">
                    <form id="MassCancelForm" method="POST" action="/cts/cancel_mass/">
                        {% csrf_token %}
                        <table class="dateFilter" cellspacing="0" cellpadding="0">

                            <tr>
                                <td class="left" style="width:180px;">
                                    <br/>
                                    Items to be Cancelled<br/>
                                    <textarea rows="20" cols="25" name="order_item" id="id_order_item">{{ sku_simple }}</textarea>
                                </td>
                                <td>
                                    <select name='cancelReason' id='id_cancelReason'>
                                        <option value='all'>{% trans "Pick a Cancel Reason" %}</option>
                                        {% for reason in reasonList %}
                                            <option value='{{ reason.pk }}'>{{ reason.name }}</option>
                                        {% endfor %}
                                    </select>
                                </td>

                            </tr>
                            <tr>
                                <td>

                                </td>
                                <td style="text-align: right;">
                                    <input id="id_submit" type="submit" name="submit" value="{% trans "cancel_all_items" %}" class="button" style="width: 100px;"/>
                                </td>
                            </tr>

                        </table>
                    </form>

                </div>
                {% if exceptionList|length > 0 %}
                    <div class="orderedErrorList">
                        <div>
                            <span class="errorMessage"> Some errors occured </span>
                        </div>
                        <br/>
                        <div class="errorPanel">
                            <ul>
                                {% for e in exceptionList %}
                                    <li>
                                        {{ e.0 }} - {{ e.1|getSmsQuickAddErrorMessage }}
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>


    <script type="text/javascript">
        $(document).ready(function(){
            displayModuleMenus("sms","list_shipment");
            setMenuName("Shipment List");

            {% if exceptionListLength > 0 %}
                skulist = "Bu ürünleri sepete eklenemiyor\n";
                {% for e in exceptionList %}
                    skulist += ("{{ e }}" + "\n");
                {% endfor %}
            {% endif %}

            $('#id_sid').val({{ supplier.pk }});
        });
    </script>
{% endblock %}